### PR TITLE
Refactored code using fmt and clippy

### PR DESCRIPTION
**Pull request by srikwit**

### CODE REVIEW

**Comment by stricaud** [comment]
Thank you very much for this contribution. It seems there are conflicts as I was also working to add the authentication yesterday, as well as some heavy cleanup.
 
Could you please have a look at resolve this with the new tree? I won't touch the code base in the meantime.

**Comment by srikwit** [comment]
Hi @stricaud, thank you for considering the pull request. However, I am unable to review the conflicts because I do not have write access to this repository.

**Comment by stricaud** [comment]
The main problem is the code was moved from src/daemon to src. There was no need to client and b64 anymore. Could you please update the tree and patch again? I am working in a branch for now, so it won't matter.

Thank you very much, and sorry for this problem as of now, you are the second contributor to the code. I will need to improve things like this, as well as adding tests. This is coming!

**Comment by srikwit** [comment]
No problem @stricaud. I will resend a pull request with the changes by today evening.

**Comment by srikwit** [comment]
@stricaud please review my pull request.

**Comment by stricaud** [comment]
Thank you very much for your great contribution!

**Comment by srikwit** [comment]
Welcome! hope to make contributions to the project.

**Pull request merged**
